/**
 * config/validateEnv.js
 *
 * Runs at boot, BEFORE anything else, and crashes the process
 * with a clear error message if required env vars are missing
 * or malformed. Warns about recommended-but-not-required vars.
 *
 * Why a comprehensive version:
 *   - Without this, a missing MONGO_URI causes a Mongoose
 *     connection error 30 seconds in.
 *   - A missing JWT_SECRET silently uses a default — fatal in
 *     production (anyone can mint admin tokens).
 *   - A missing PAWAPAY_WEBHOOK_SECRET means webhook
 *     signature verification can't be performed — fatal.
 *
 * The validator is split into REQUIRED (crash) and RECOMMENDED
 * (warn). The lists below cover everything the codebase
 * actually reads — generated by `git grep -h "process.env"`
 * across `backend/src/` then deduped + categorized.
 *
 * Add to this file when introducing new env vars.
 */

const REQUIRED = [
    {
        name: 'NODE_ENV',
        validator: v => ['development', 'production', 'test', 'staging'].includes(v),
        hint: 'must be one of: development, production, test, staging'
    },
    {
        name: 'MONGO_URI',
        validator: v => /^mongodb(\+srv)?:\/\//.test(v),
        hint: 'should be a mongodb:// or mongodb+srv:// URI'
    },
    {
        name: 'JWT_SECRET',
        validator: v => typeof v === 'string' && v.length >= 32,
        hint: 'must be at least 32 characters of high-entropy randomness'
    },
    {
        name: 'JWT_REFRESH_SECRET',
        validator: v => typeof v === 'string' && v.length >= 32,
        hint: 'must be at least 32 characters, DIFFERENT from JWT_SECRET'
    }
];

// Production-only required
const REQUIRED_IN_PRODUCTION = [
    {
        name: 'ALLOWED_ORIGINS',
        validator: v => typeof v === 'string' && v.length > 0,
        hint: 'comma-separated list of allowed CORS origins (no localhost in prod!)'
    },
    {
        name: 'PAWAPAY_WEBHOOK_SECRET',
        validator: v => typeof v === 'string' && v.length >= 16,
        hint: 'PawaPay webhook signing key — REQUIRED for webhook verification'
    },
    {
        name: 'PAWAPAY_API_KEY',
        validator: v => typeof v === 'string' && v.length > 0,
        hint: 'PawaPay API key'
    },
    {
        name: 'FRONTEND_URL',
        validator: v => /^https:\/\//.test(v),
        hint: 'should be the HTTPS URL of the public frontend'
    }
];

const RECOMMENDED = [
    { name: 'PORT',                   hint: 'defaults to 1000' },
    { name: 'EMAIL_FROM',             hint: 'for transactional emails (reset, verify, receipts)' },
    { name: 'EMAIL_SMTP_HOST',        hint: 'SMTP host for outbound mail' },
    { name: 'EMAIL_SMTP_USER',        hint: 'SMTP user' },
    { name: 'EMAIL_SMTP_PASS',        hint: 'SMTP password' },
    { name: 'STATIC_UPLOADS_PATH',    hint: 'where multer writes uploaded files; defaults to ./uploads' },
    { name: 'STATIC_MUSIC_PATH',      hint: 'where static music files are served from' },
    { name: 'STATIC_IMAGES_PATH',     hint: 'where static images are served from' },
    { name: 'AWS_S3_BUCKET',          hint: 'if using S3 for uploads instead of local disk' },
    { name: 'AWS_ACCESS_KEY_ID',      hint: 'paired with the bucket' },
    { name: 'AWS_SECRET_ACCESS_KEY',  hint: 'paired with the bucket' },
    { name: 'AWS_REGION',             hint: 'paired with the bucket' },
    { name: 'PAWAPAY_BASE_URL',       hint: 'PawaPay API base URL (sandbox vs production)' },
    { name: 'BACKUP_S3_BUCKET',       hint: 'where mongodump backups go' }
];

// Vars whose presence in DEV but absence in PROD is a red flag
// (these are insecure defaults you'd want disabled before deploying)
const PRODUCTION_FORBIDDEN = [
    'DEBUG',
    'ENABLE_TEST_ROUTES',
    'BYPASS_AUTH',
    'BYPASS_WEBHOOK_VERIFY',
    'SEED_ON_BOOT'
];

export function validateEnv() {
    const env = process.env.NODE_ENV || 'development';
    const isProduction = env === 'production';

    const errors = [];
    const warnings = [];

    // Required
    for (const r of REQUIRED) {
        const v = process.env[r.name];
        if (v === undefined || v === '') {
            errors.push(`MISSING ${r.name} — ${r.hint}`);
        } else if (r.validator && !r.validator(v)) {
            errors.push(`INVALID ${r.name} — ${r.hint}`);
        }
    }

    // Required in production
    if (isProduction) {
        for (const r of REQUIRED_IN_PRODUCTION) {
            const v = process.env[r.name];
            if (v === undefined || v === '') {
                errors.push(`MISSING ${r.name} (production) — ${r.hint}`);
            } else if (r.validator && !r.validator(v)) {
                errors.push(`INVALID ${r.name} (production) — ${r.hint}`);
            }
        }

        // Cross-checks: secrets must be different
        if (process.env.JWT_SECRET === process.env.JWT_REFRESH_SECRET) {
            errors.push('JWT_SECRET and JWT_REFRESH_SECRET must be DIFFERENT values');
        }

        // Forbidden in production
        for (const name of PRODUCTION_FORBIDDEN) {
            if (process.env[name]) {
                errors.push(`FORBIDDEN ${name} is set in production — remove from env`);
            }
        }

        // Detect very obviously default / placeholder values
        const placeholderPatterns = [/changeme/i, /example/i, /your-/i, /placeholder/i, /todo/i];
        for (const r of [...REQUIRED, ...REQUIRED_IN_PRODUCTION]) {
            const v = process.env[r.name] || '';
            for (const pat of placeholderPatterns) {
                if (pat.test(v)) {
                    errors.push(`PLACEHOLDER value detected for ${r.name}: looks like an unset template value`);
                    break;
                }
            }
        }
    }

    // Recommended
    for (const r of RECOMMENDED) {
        if (process.env[r.name] === undefined) {
            warnings.push(`RECOMMENDED ${r.name} not set — ${r.hint}`);
        }
    }

    // Emit warnings (non-fatal)
    for (const w of warnings) {
        console.warn(`[env] ${w}`);
    }

    // Emit errors (fatal)
    if (errors.length > 0) {
        console.error('');
        console.error('========================================');
        console.error('ENV VALIDATION FAILED');
        console.error('========================================');
        for (const e of errors) {
            console.error(`  - ${e}`);
        }
        console.error('');
        console.error('Server cannot start. Fix the above and restart.');
        console.error('See .env.example for the canonical list of env vars.');
        console.error('========================================');
        process.exit(1);
    }

    console.log(`[env] Validated (env=${env}, ${REQUIRED.length} required + ${isProduction ? REQUIRED_IN_PRODUCTION.length : 0} prod-required)`);
}

export default validateEnv;
